### ISSUE TITLE
Unable to do npm install

### ISSUE THREAD

**Issue by fredrikj** [node-webrtc/node-webrtc-examples#1]
Trying to do `npm install` I get the following output:

```
node-webrtc-examples - master ❯ npm i

> fsevents@1.2.9 install /Users/fred/git/node-webrtc-examples/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
[fsevents] Success: "/Users/fred/git/node-webrtc-examples/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> canvas@2.5.0 install /Users/fred/git/node-webrtc-examples/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[canvas] Success: "/Users/fred/git/node-webrtc-examples/node_modules/canvas/build/Release/canvas.node" is installed via remote

> wrtc@0.3.7 install /Users/fred/git/node-webrtc-examples/node_modules/wrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.7/Release/node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/Users/fred/git/node-webrtc-examples/node_modules/node-pre-gyp/lib/install.js:139:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:201:15)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/Users/fred/git/node-webrtc-examples/node_modules/needle/lib/needle.js:482:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:284:20)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:196:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:196:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:290:12)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/Users/fred/git/node-webrtc-examples/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /Users/fred/git/node-webrtc-examples/node_modules/wrtc
node-pre-gyp ERR! node -v v12.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.3.7/Release/node-v72-darwin-x64.tar.gz
Unable to install a pre-built wrtc binary; falling back to ncmake
Running ncmake configure
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/local/bin/git (found version "2.21.0")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Downloading: https://nodejs.org/download/release/v12.1.0/SHASUMS256.txt
-- NodeJS: Using node, version v12.1.0
-- Downloading: https://nodejs.org/download/release/v12.1.0/node-v12.1.0-headers.tar.gz
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/fred/git/node-webrtc-examples/node_modules/wrtc/build
Running ncmake build
ninja: error: 'external/libwebrtc/build/Release/obj/pc/libpeerconnection.a', needed by 'Release/wrtc.node', missing and no known rule to make it
Build failed
/Users/fred/git/node-webrtc-examples/node_modules/wrtc/scripts/install.js:59
    throw new Error('ncmake build failed for wrtc');
    ^

Error: ncmake build failed for wrtc
    at build (/Users/fred/git/node-webrtc-examples/node_modules/wrtc/scripts/install.js:59:11)
    at download (/Users/fred/git/node-webrtc-examples/node_modules/wrtc/scripts/install.js:40:5)
    at Object.<anonymous> (/Users/fred/git/node-webrtc-examples/node_modules/wrtc/scripts/install.js:67:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wrtc@0.3.7 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.3.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fred/.npm/_logs/2019-05-29T12_46_32_556Z-debug.log
```

**Comment by seandlg** [comment]
I had a similar problem and leaving this here for whoever might stumble across this. It seems like `wrtc` is missing and the download fails (see the 404), `ncmake` fails as well (for reasons I don't comprehend). A simple fix for me was to:
```
cd ..
git clone https://github.com/node-webrtc/node-webrtc
cd node-webrtc
npm i
cp -r node_modules/wrtc/ ../node-webrtc-examples/node_modules/
cd ../node-webrtc-examples
npm test
npm start
```
Pretty sure that's not how you're supposed to do things, but it got the demo working for me in a matter of 2 minutes.

**Comment by markandrus** [comment]
That's funny. I think 0.3.7 was broken for a short while (file missing). Should be fixed now.

**Comment by Mouradif** [comment]
I have this problem with 0.4.6

**Comment by verekia** [comment]
Same problem when installing `wrtc` 0.4.7 or this example on my Mac M1:
`404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz`

**Comment by aryanjain28** [comment]
@verekia 
Hey did you find any solution?

**Comment by verekia** [comment]
@aryanjain28 I haven't looked into it, sorry :) If you are looking for an alternative option, I ended up using uWebSockets.js, a performant WebSocket library.
