### ISSUE TITLE
cannot save mp4 for example record-audio-video-stream at windows platform

### ISSUE THREAD

**Issue by manhingcctil** [node-webrtc/node-webrtc-examples#15]
I would like to run record-audio-video-stream at windows platform, but it seems the program only support UnixStream. May I know if it is possible to provide a window platform example for this. Thanks a lot.

Error: listen EACCES: permission denied ./1.sock
    at Server.setupListenHandle [as _listen2] (net.js:1273:19)
    at listenInCluster (net.js:1338:12)
    at Server.listen (net.js:1436:5)
    at new UnixStream (E:\node-webrtc-examples-master\node_modules\fluent-ffmpeg-multistream\src\index.js:18:12)
    at new StreamInput (E:\node-webrtc-examples-master\node_modules\fluent-ffmpeg-multistream\src\index.js:23:10)

**Comment by kenfouo** [comment]
> Je voudrais exécuter un flux d'enregistrement audio-vidéo sur la plate-forme Windows, mais il semble que le programme ne supporte que UnixStream. Puis-je savoir s'il est possible de fournir un exemple de plate-forme de fenêtre pour cela. Merci beaucoup.
> 
> Erreur: Listen EACCES: permission refusée ./1.sock
> sur Server.setupListenHandle [as _listen2] (net.js: 1273: 19)
> sur listenInCluster (net.js: 1338: 12)
> sur Server.listen (net.js: 1436 : 5)
> au nouveau UnixStream (E: \ node-webrtc-examples-master \ node_modules \ fluent-ffmpeg-multistream \ src \ index.js: 18: 12)
> au nouveau StreamInput (E: \ node-webrtc-examples-master \ node_modules \ fluent-ffmpeg-multistream \ src \ index.js: 23: 10)

I have the same problem; any help will be welcome thank you

**Comment by rajatjindal007** [comment]
I am having the same issue. Need this for developing my solution on my workstation which is windows 10

events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied ./1.sock
    at Server.setupListenHandle [as _listen2] (net.js:1292:21)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1456:5)
    at new UnixStream

**Comment by wnabil** [comment]
its a windows write file permission issue, nothing appears on linux
